server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/bling_test
    username: bling_test
    password: 9TTk5oEVAWwikv6i

